### ISSUE TITLE
batch download with lowest settings

### ISSUE THREAD

**Issue by Abdullah-Abusamra** [icexmoon/haokan-download#1]
I don't know much about coding but i tried to fix it , as i needed the highest quality to be downloaded .

My fix is simple and stupid which is happened in this path:
C:\Users\%user%\AppData\Local\Programs\Python\Python39\Lib\site-packages\you_get\extractors\Haokan.py

at line 11 just reverse the order.
stream_types = [
        {'id': '1080p','container': 'MP4','quality':1080,'video_profile': '1080p', 'desc': '蓝光'},
        {'id': 'sc','container': 'MP4','quality':720, 'video_profile': '720p', 'desc': '超清'},
        {'id': 'hd','container': 'MP4','quality':480,'video_profile': '480p', 'desc': '高清'},
        {'id': 'sd','container': 'MP4','quality':360,'video_profile': '360p', 'desc': '标清'},
    ]

and it worked for me...

thank you

**Comment by icexmoon** [comment]
Thanks for the feedback, I did not encounter this problem, I wrote the main body of the program is a crawler, you-get is only to download the video plug-in program
